port: 3000
b2:
  accountId: accountId
  applicationKey: applicationKey
  bucketId: bucketId
  digest:
    algorithm: sha1
db:
  type: 'elasticsearch'
  apiVersion: '5.0'
  hosts:
   - localhost
  port: 9200
  protocol: http
  user: user
  password: password
  log:
    level: trace
    path: './elasticsearch.log'
    type: file
  index: files
fb:
  appId: appId
  appSecret: appSecret
logger:
  level: debug
  file:
    path: './api.log'
upload:
  maxFileSize: 209715200 # 200MB
  image:
    metadata:
      bufferFields:
       - ExifVersion
       - FileSource
       - FlashpixVersion
       - icc
       - SceneType
      exifFields:
       - ApertureValue
       - ColorSpace
       - DateTimeDigitized
       - DateTimeOriginal
       - ExifVersion
       - ExposureTime
       - Flash
       - FNumber
       - FocalLength
       - ISO
       - ShutterSpeedValue
      exifImageFields:
       - Make
       - Model
       - Software
       - ModifyDate
      metaFields:
       - channels
       - density
       - format
       - hasProfile
       - hasAlpha
       - height
       - orientation
       - space
       - width
    thumbnail:
      formats:
       - jpeg
       - webp
      sizes:
       - 90
       - 180
       - 270
       - 960
  supportedMimeTypes:
   - 'image/jpeg'
  tempDir: './tmp'
